export const ICON_MAP = {
  meditate: 'fas fa-om',
  run: 'fas fa-running',
  bike: 'fas fa-biking',
  journal: 'fas fa-feather-alt',
  swim: 'fas fa-swimmer',
  exercise: 'fas fa-dumbbell',
  sweets: 'fas fa-ice-cream',
  drink: 'fas fa-wine-glass',
  coffee: 'fas fa-mug-hot',
  ball: 'fas fa-basketball-ball',
  smoking: 'fas fa-smoking',
  dog: 'fas fa-dog',
  book: 'fas fa-book',
  pray: 'fas fa-pray',
  pills: 'fas fa-pills',
  food: 'fas fa-utensils',
  veggetables: 'fas fa-leaf',
  fruits: 'fas fa-apple-alt',
  money: 'fas fa-money-bill-wave',
  business: 'fas fa-suitcase',
  phone: 'fas fa-phone',
  listen: 'fas fa-headphones-alt',
  clean: 'fas fa-broom',
  shower: 'fas fa-shower',
  gaming: 'fas fa-gamepad',
  coding: 'fas fa-code'
}
