export const ICON_MAP = {
  question: 'fas fa-question-circle',
  meditate: 'fas fa-om',
  run: 'fas fa-running',
  bike: 'fas fa-biking',
  journal: 'fas fa-feather-alt',
  paint: 'fas fa-palette',
  writing: 'fas fa-pen',
  swim: 'fas fa-swimmer',
  guitar: 'fas fa-guitar',
  exercise: 'fas fa-dumbbell',
  sweets: 'fas fa-ice-cream',
  drink: 'fas fa-wine-glass',
  water: 'fas fa-glass-whiskey',
  coffee: 'fas fa-mug-hot',
  ball: 'fas fa-basketball-ball',
  smoking: 'fas fa-smoking',
  dog: 'fas fa-dog',
  friends: 'fas fa-user-friends',
  book: 'fas fa-book',
  pray: 'fas fa-pray',
  pills: 'fas fa-pills',
  food: 'fas fa-utensils',
  veggetables: 'fas fa-leaf',
  fruits: 'fas fa-apple-alt',
  money: 'fas fa-money-bill-wave',
  business: 'fas fa-suitcase',
  phone: 'fas fa-phone',
  smartphone: 'fas fa-mobile-alt',
  listen: 'fas fa-headphones-alt',
  clean: 'fas fa-broom',
  shower: 'fas fa-shower',
  gaming: 'fas fa-gamepad',
  coding: 'fas fa-code',
  sleep: 'fas fa-bed'
}
export const EMOJI_MAP = {
  question: '❓',
  meditate: '🧘',
  run: '🏃',
  bike: '🚴',
  journal: '📔',
  paint: '🎨',
  writing: '✍️',
  swim: '🏊',
  guitar: '🎸',
  exercise: '🏋️',
  sweets: '🧁',
  drink: '🍹',
  water: '🌊',
  coffee: '☕',
  ball: '⚽',
  smoking: '🚬',
  dog: '🐶',
  friends: '👨‍👩‍👧‍👦',
  book: '📖',
  pray: '🙏',
  pills: '💊',
  food: '🍽️',
  veggetables: '🍽️',
  fruits: '🍌',
  money: '💶',
  business: '💼',
  phone: '📞',
  smartphone: '📱',
  listen: '🎧',
  clean: '🧹',
  shower: '🛀',
  gaming: '🎮',
  coding: '💻',
  sleep: '🛌'
}

export const CATEGORY_MAP = [
  { label: 'Physical Health', value: 'physical-health' },
  { label: 'Mental Health', value: 'mental-health' },
  { label: 'Relationships', value: 'relationships' },
  { label: 'Career', value: 'career' },
  { label: 'Hobbies', value: 'hobbies' }
]

export const ALLOWED_HABIT_FIELDS = [
  'author',
  'category',
  'description',
  'duration',
  'frequency',
  'icon',
  'loggedDays',
  'members',
  'perMonth',
  'perWeek',
  'privacy',
  'reminders',
  'specificDays',
  'stake',
  'startDate',
  'title',
  'repeated',
  'archived'
]
